# data source file
---
datasources:
  - name: data-base-1
    strategy: Mysql  # this property is optional
    url: jdbc:mysql://uamed.mysql.ukraine.com.ua/uamed_chefua?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    table: user
    user: uamed_chefua
    password: JMca3^x4-1
    mapping:
      id: user_id
      username: username
      name: firstname
      surname: lastname
  - name: data-base-2
    strategy: MySql
    url: jdbc:mysql://uamed.mysql.ukraine.com.ua/uamed_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    table: user
    user: uamed_db
    password: rr2JFttn
    mapping:
      id: user_id
      username: username
      name: firstname
      surname: lastname
