# data source file
---
datasources:
  - name: uamed_db
    strategy: Mysql  # this property is optional
    url: jdbc:postgresql://localhost:5432/postgres
    table: user
    user: sa
    password: sa
    mapping:
      id: user_id
      username: username
      name: firstname
      surname: lastname
  - name: uamed_db
    strategy: MySql
    url: jdbc:postgresql://localhost:5432/postgres
    table: user
    user: sa
    password: sa
    mapping:
      id: user_id
      username: username
      name: firstname
      surname: lastname
